//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    //public partial class JobContext : DbContext
    //{
    //    public JobContext()
    //        : base("name=CentralDBEntities1")
    //    {
    //    }
    
    //    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    //    {
    //        throw new UnintentionalCodeFirstException();
    //    }
    
    //    public virtual DbSet<Job> Jobs { get; set; }
    //    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    //    public virtual DbSet<User> Users { get; set; }
        
    //}
}
