//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string Company { get; set; }
        public string Role { get; set; }
        public string Language { get; set; }
        public string Distcance { get; set; }
        public string Date { get; set; }
        public string City { get; set; }
    }
}
